
post http://localhost:3001/products
content-Type: application/json

{
    "image": "image3"
}
#######

get http://localhost:3001/products
content-Type: application/json

#######

post http://localhost:3001/auth
content-Type: application/json

{
    "username": "nadia",
    "password": "password"
}
#######

post http://localhost:3001/auth/login
content-Type: application/json

{
    "username": "pavel",
    "password": "pavel"
}
#######